### ISSUE TITLE
LED for PIR detection.

### ISSUE THREAD

**Issue by askthomas** [ESPresense/ESPresense#379]
**Is your feature request related to a problem? Please describe.**
Option to add LED for PIR detetion

**Describe the solution you'd like**
When PIR detection is made, it would be nice to have an LED to light up,

**Comment by simonyel** [comment]
I would like to have an option to add a RGB cathode LED to the mix and port it as an entity to HA. That way I can show the status inside all the ESPresense enabled rooms.  Ex: White as a night light, RED as alarm set, GREEN flash as device detected, BLUE flash as BLE beacon detected, etc. would be a very powerful add-on. I do this with all my ESPhome devices, but since BLE isn't a component there I'm looking to migrate.

**Comment by DTTerastar** [comment]
Yeah, I agree.  It would be nice to have the led controllable via an entity.

**Comment by DTTerastar** [comment]
This is implemented in v3.  Set the pins on led 1, 2, and 3 to the pins of the led on pwm and it should work!
