### ISSUE TITLE
Wildcards for excluded devices

### ISSUE THREAD

**Issue by joshuamckay** [ESPresense/ESPresense#497]
**Is your feature request related to a problem? Please describe.**
In busy environments such as dense housing, many unrelated devices are populated, requiring exclusion of literally hundreds of ble devices to optimize mqtt traffic.

**Describe the solution you'd like**
The ability to exclude "sonos:*" and "apple:*" for instance, to exclude a neighbors 5 sonos and 10 apple devices, while still allowing the rest to flow through. Even better would be ability to exclude via regex or something, such that a user could filter out certain lengths/patterns. This could be helpful for the include side as well, if you know you only want to see "apple:*" for instance.

**Describe alternatives you've considered**
I can of course whitelist the include side to filter out unwanted topics, but that doesn't really solve for trying to identify new devices.

**Comment by DTTerastar** [comment]
you can exclude several prefixes, just separate them with a space char.

**Comment by broyuken** [comment]
can you do wildcards in the exclusions though? Can you exclude apple* or do you have to do apple:1005:9-8 apple:1005:9-24 apple:1006:10-7 apple:1006:10-8 apple:1007:11-6 apple:1007:11-7 apple:1007:11-12

You can see how this could get really annoying to upkeep as more and more things show up around you. I would like to exclude iBeacon* instead of excluding each individual iBeacon that is found and reported to mqtt.

**Comment by DTTerastar** [comment]
IBeacon without the * will exclude everything that starts with iBeacon.  The * at the end is implied.  It's a list of "prefixes"

**Comment by Exit2Studios** [comment]
I realize this is old, but can someone confirm that you should be able to exclude all devices that start with "apple:findmy" by entering apple:findmy in the exclude filter area?  Doesn't seem to be working.
