### ISSUE TITLE
unique_id: not allowed?

### ISSUE THREAD

**Issue by vzoltan** [ESPresense/ESPresense#510]
![image](https://user-images.githubusercontent.com/2751780/176390423-370eebda-23bb-4bc1-b78b-1581a375bc67.png)

could you please add unique_id support, ir it is not allowed by home assistant for mqtt_room ?

Thanks

**Comment by DTTerastar** [comment]
That's totally a home assistant thing.  Most yaml configured entities don't use unique_id since you can change it in yaml.  You should request this in their repo if needed.

**Comment by vzoltan** [comment]
ok, thanks

**Comment by andrelung** [comment]
Sorry for commenting on a closed issue, I can't figure it our and hope that @vzoltan has some insight into this.

I can't get the IDs working in home assistant:
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/4161059/196033779-15f63908-1444-40f2-8822-6817ff1d0c0a.png">

After clicking on the device:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/4161059/196033837-982813f7-4d3f-4b73-bea3-1cca26ab3f9e.png">

> This entity ('sensor.es_presence_al_13') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

Per HA-configuration it looks like I should add `entity_id` or `unique_id` but this isn't allowed by mqtt_room. What's the right way to change add my devices sensor, so that they use an unique id?
