### ISSUE TITLE
Update Button

### ISSUE THREAD

**Issue by VACIndustries** [ESPresense/ESPresense#533]
Requesting a feature to the UI where you can force the update to the latest (or beta if you're checked for it) via an "update" button instead of waiting for it to happen automatically.

**Comment by DTTerastar** [comment]
Upvote this: https://community.home-assistant.io/t/mqtt-discovery-for-the-new-update-sensor/427146

**Comment by blacknell** [comment]
Is there an MQTT topic so force an upgrade?

**Comment by DTTerastar** [comment]
yes /update/set with any value sent to it

**Comment by DTTerastar** [comment]
In v3 you can send a http/https url and it'll install that exact version.  Can be used to switch firmware flavors without serial!

**Comment by Powerdata44** [comment]
> yes /update/set with any value sent to it

what value?

**Comment by N3rdix** [comment]
> > yes /update/set with any value sent to it
> 
> what value?

as mentioned **any** value is possible, i just sent a raw `1` to the topic and the update went through

**Comment by Powerdata44** [comment]
Am trying to understand on it.

At moment esp32 with espresense firmware hidden above ceiling in centre of room, connected to WiFi. Old firmware at moment.

Like to upgrade firmware to newer - can it be done through MQTT with typed as you mentioned  /update/set with add 1 in raw then will upgrade newer firmware.

Am I correct? 

Or need to do with OTA - if so how?




Where get url / https  or just

**Comment by N3rdix** [comment]
if you are on the version which introduced https://github.com/ESPresense/ESPresense/pull/595 then of course you can update via MQTT. Otherwise why not accessing the local UI via `http://<IP>` and either select "update automatically" or enter the update URL (which should be a bin file from the release, e.g. https://github.com/ESPresense/ESPresense/releases/tag/v3.3.2)

Via MQTT here's my example topic which triggered the update. Hope that makes it clear.

![image](https://github.com/user-attachments/assets/08bbda55-9161-4137-82eb-8e517ac36694)

**Comment by Powerdata44** [comment]
Now I can see new update version v3.3.5 so where can I get url from in github site?

So I can add it in setting in esp32 device (hidden above ceiling mean need update via OTA.

**Comment by N3rdix** [comment]
Depends on your device, the ota files are always linked in the release, e.g.:

https://github.com/ESPresense/ESPresense/releases/download/v3.3.5/esp32.bin
