### ISSUE TITLE
Completely remove espresense from ESP32

### ISSUE THREAD

**Issue by pickonedev** [ESPresense/ESPresense#545]
Hi!

Can someone please tell me how can I wipe ESP32 completely? Like a factory reset...
I tried with `py -m esptool --chip ESP32 --port COM5 erase_flash` but espresense it is still there...

Thank you in advance!

**Comment by hellcry37** [comment]
Write something else over it? Use ESP32 for whatever else you want! I'am no expert but I don't think you can factory clean esp32 chip.

**Comment by pickonedev** [comment]
> Write something else over it? Use ESP32 for whatever else you want! I'am no expert but I don't think you can factory clean esp32 chip.

I tried, but no result...

**Comment by pickonedev** [comment]
> https://docs.espressif.com/projects/esptool/en/latest/esp32s3/esptool/basic-commands.html that says erase_flash should have worked. Do you have more than one connected to usb perhaps?

No, only one used... I tried to install Ultrasonic Sensor with ESPHome from home assistant, and you can see that the ESPresense it is still there...  Take a look at the image
![Untitled](https://user-images.githubusercontent.com/34201387/179021471-2d690629-a939-4827-b2cf-657999635986.jpg)

**Comment by FsFalcon** [comment]
@pickonedev - If the issue is that you no longer want the device in Home Assistant, you'll need to remove it by purging the MQTT auto-discovery topics from your MQTT server.  This can be done with a program like [MQTT Explorer](http://mqtt-explorer.com/).

Once connected to your broker, purge any of the topics associated with the device from the homeassistant/[sensor_type]/topics  You can find the appropriate entries to purge from the 'MQTT Info' option on the device in HA.
![2022-07-14_10-46-57](https://user-images.githubusercontent.com/13118741/179023597-8f1cc7b6-810c-4c0f-a71d-e29603633770.png)

**Comment by pickonedev** [comment]
Uuuuuuu, nice, Thank you!
