### ISSUE TITLE
Save SGP30 baseline 

### ISSUE THREAD

**Issue by rjbutler** [ESPresense/ESPresense#796]
### Is your feature request related to a problem? Please describe.

It does not appear that the baseline calibration value is being saved.  Saving and restoring the baseline value will avoid the 12 hour re-calibration on start and provide more accurate readings.   If I read the documentation correctly, the initial baseline can be read after 12 hours and saved for later restoration on startup.

**Comment by radkokeves** [comment]
Hi there!

if anyone is interested in implemented baseline as you described
here it is:
https://github.com/radkokeves/ESPresense_m5stickcplus_sgp30-baseline

based on 
https://files.seeedstudio.com/wiki/Grove-VOC_and_eCO2_Gas_Sensor-SGP30/res/Sensirion_Gas_Sensors_SGP30_Driver-Integration-Guide_HW_I2C.pdf
https://sensirion.com/media/documents/984E0DD5/61644B8B/Sensirion_Gas_Sensors_Datasheet_SGP30.pdf
https://github.com/adafruit/Adafruit_SGP30/blob/master/Adafruit_SGP30.cpp
https://registry.platformio.org/libraries/adafruit/Adafruit%20SGP30%20Sensor/examples/sgp30test/sgp30test.ino

i created my own namespace TVOC_SGP30 instead of SensirionSGP30 it was easier for me to play with

there are some ESPresense customizations related to M5StickC-plus because i wanted M5 API to play with (display brightness...)

hope it helps
